services:
  qb-connector:
    image: qb:latest
    container_name: qb
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - SERVER_URL=https://infinitecapi.online
    restart: unless-stopped
    volumes:
      - /opt/ssl/infinitecapi:/certs:ro
    networks:
      - portainer_net
      - shared-network

networks:
  portainer_net:
    driver: bridge
  shared-network:
    driver: bridge
    external: true